# This workflow will install Rust dependencies, run formatters / linters / build, and execute the binary
name: Run Script

# Execute job at the given timing:
# 12pm UTC on the 1st of every month
# https://crontab.guru/#0_12_1_*_*
on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.62.0
            override: true
            components: rustfmt, clippy
      - name: Run build
        run: |
          cargo build --release
      - name: Run
        run: |
          cargo run --release
        env:
          VENMO_ACCESS_TOKEN: ${{ secrets.VENMO_ACCESS_TOKEN }}
          FRIEND_ID: ${{ secrets.FRIEND_ID }}
